!git: Disable LFS Git hooks

diff --git a/linux/.gitconfig_files/hooks/pre-push b/linux/.gitconfig_files/hooks/pre-push
--- a/linux/.gitconfig_files/hooks/pre-push
+++ b/linux/.gitconfig_files/hooks/pre-push
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
-git lfs pre-push "$@"
+# command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
+# git lfs pre-push "$@"
 
 # Execute hook of current repository
 if [ -f .git/hooks/`basename $0` ] && [ -x .git/hooks/`basename $0` ]; then
